# Generated by Django 4.0.2 on 2022-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_blog_date_created_alter_blog_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.IntegerField(choices=[(1, 'News'), (2, 'Advertisement'), (3, 'Memo')], default=1),
            preserve_default=False,
        ),
    ]
