# Generated by Django 4.0.2 on 2022-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.IntegerField(choices=[(1, 'News'), (2, 'Advertisement'), (3, 'Memo')], default=1),
        ),
    ]
