# Generated by Django 4.0.2 on 2022-04-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
