# Generated by Django 4.0.2 on 2022-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reporter',
            options={},
        ),
    ]
