# Generated by Django 4.0.2 on 2022-04-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Student'),
        ),
    ]
